### ISSUE TITLE
Parse markdown error

### ISSUE THREAD

**Issue by Michael18811380328** [byrnereese/mkdocs-minify-plugin#17] opened 2021-10-27 03:26 UTC
When I use default mkdocs settings, markdown can compile to html correctly,  howerer, when I use this plugin to minify mkdocs html, there is an error.

mkdocs-minify-plugin version is 0.5.0, how to solve this problem?

```
ERROR    -  Error building page 'nodejs/17-Node.js GETPOST.md':
Traceback (most recent call last):
  File "/mypath/py3env/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
  File "/mypath/py3env/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/mypath/py3env/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/mypath/py3env/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/mypath/py3env/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/mypath/py3env/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/mypath/py3env/lib/python3.7/site-packages/mkdocs/__main__.py", line 183, in build_command
    build.build(config.load_config(**kwargs), dirty=not clean)
  File "/mypath/py3env/lib/python3.7/site-packages/mkdocs/commands/build.py", line 306, in build
    _build_page(file.page, config, doc_files, nav, env, dirty)
  File "/mypath/py3env/lib/python3.7/site-packages/mkdocs/commands/build.py", line 221, in _build_page
    'post_page', output, page=page, config=config
  File "/mypath/py3env/lib/python3.7/site-packages/mkdocs/plugins.py", line 94, in run_event
    result = method(item, **kwargs)
  File "/mypath/py3env/lib/python3.7/site-packages/mkdocs_minify_plugin/plugin.py", line 79, in on_post_page
    return minify(output_content, opts.get("remove_comments", False), opts.get("remove_empty_space", False), opts.get("remove_all_empty_space", False), opts.get("reduce_empty_attributes", True), opts.get("reduce_boolean_attributes", False), opts.get("remove_optional_attribute_quotes", True), opts.get("convert_charrefs", True), opts.get("keep_pre", False), opts.get("pre_tags", ('pre', 'textarea')), opts.get("pre_attr", 'pre'))
  File "/mypath/py3env/lib/python3.7/site-packages/htmlmin/main.py", line 105, in minify
    minifier.feed(input)
  File "/mypath/py3env/lib/python3.7/site-packages/htmlmin/python3html/parser.py", line 125, in feed
    self.goahead(0)
  File "/mypath/py3env/lib/python3.7/site-packages/htmlmin/python3html/parser.py", line 185, in goahead
    k = self.parse_starttag(i)
  File "/mypath/py3env/lib/python3.7/site-packages/htmlmin/python3html/parser.py", line 359, in parse_starttag
    self.handle_starttag(tag, attrs)
  File "/mypath/py3env/lib/python3.7/site-packages/htmlmin/parser.py", line 271, in handle_starttag
    self._in_pre_tag -= self._close_tags_up_to(t[0])
  File "/mypath/py3env/lib/python3.7/site-packages/htmlmin/parser.py", line 254, in _close_tags_up_to
    raise OpenTagNotFoundError()
htmlmin.parser.OpenTagNotFoundError
```

**Comment by wilhelmer** [comment] 2022-10-20 09:12
Sorry for not looking into this. I can't reproduce it, does the issue still persist? Otherwise, I'll close this.

**Closed** 2022-10-21 06:32 UTC
